export type AssetType = "crypto" | "forex" | "commodity" | "index" | "stock" | "etf";

export interface AssetMeta {
  slug: string;
  name: string;
  symbol: string;
  type: AssetType;
  coingeckoId?: string;
  finnhubSymbol: string;
  logoUrl: string;
  fallbackColor: string;
  description: string;
  displayDecimals: number;
}

const crypto: AssetMeta[] = [
    { slug: "bitcoin", name: "Bitcoin", symbol: "BTC", type: "crypto", coingeckoId: "bitcoin", finnhubSymbol: "BINANCE:BTCUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400", fallbackColor: "#e67437", displayDecimals: 2, description: "Plus grande capitalisation crypto mondiale, leader du secteur" },
    { slug: "ethereum", name: "Ethereum", symbol: "ETH", type: "crypto", coingeckoId: "ethereum", finnhubSymbol: "BINANCE:ETHUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628", fallbackColor: "#3191c8", displayDecimals: 2, description: "Plus grande capitalisation crypto mondiale, leader du secteur" },
    { slug: "tether", name: "Tether", symbol: "USDT", type: "crypto", coingeckoId: "tether", finnhubSymbol: "BINANCE:USDTUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661", fallbackColor: "#cabb8f", displayDecimals: 4, description: "Plus grande capitalisation crypto mondiale, leader du secteur" },
    { slug: "binancecoin", name: "BNB", symbol: "BNB", type: "crypto", coingeckoId: "binancecoin", finnhubSymbol: "BINANCE:BNBUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970", fallbackColor: "#3ab5a0", displayDecimals: 2, description: "Plus grande capitalisation crypto mondiale, leader du secteur" },
    { slug: "usd-coin", name: "USDC", symbol: "USDC", type: "crypto", coingeckoId: "usd-coin", finnhubSymbol: "BINANCE:USDCUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602", fallbackColor: "#90a85d", displayDecimals: 4, description: "Plus grande capitalisation crypto mondiale, leader du secteur" },
    { slug: "ripple", name: "XRP", symbol: "XRP", type: "crypto", coingeckoId: "ripple", finnhubSymbol: "BINANCE:XRPUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442", fallbackColor: "#757186", displayDecimals: 2, description: "Projet blockchain majeur, capitalisation top 15, large adoption" },
    { slug: "solana", name: "Solana", symbol: "SOL", type: "crypto", coingeckoId: "solana", finnhubSymbol: "BINANCE:SOLUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756", fallbackColor: "#c131f4", displayDecimals: 2, description: "Projet blockchain majeur, capitalisation top 15, large adoption" },
    { slug: "tron", name: "TRON", symbol: "TRX", type: "crypto", coingeckoId: "tron", finnhubSymbol: "BINANCE:TRXUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/1094/large/photo_2026-04-13_09-59-16.png?1776048311", fallbackColor: "#3fc186", displayDecimals: 4, description: "Projet blockchain majeur, capitalisation top 15, large adoption" },
    { slug: "figure-heloc", name: "Figure Heloc", symbol: "FIGR_HELOC", type: "crypto", coingeckoId: "figure-heloc", finnhubSymbol: "BINANCE:FIGR_HELOCUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954", fallbackColor: "#14fe93", displayDecimals: 2, description: "Projet blockchain majeur, capitalisation top 15, large adoption" },
    { slug: "hyperliquid", name: "Hyperliquid", symbol: "HYPE", type: "crypto", coingeckoId: "hyperliquid", finnhubSymbol: "BINANCE:HYPEUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300", fallbackColor: "#a27271", displayDecimals: 2, description: "Projet blockchain majeur, capitalisation top 15, large adoption" },
    { slug: "dogecoin", name: "Dogecoin", symbol: "DOGE", type: "crypto", coingeckoId: "dogecoin", finnhubSymbol: "BINANCE:DOGEUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409", fallbackColor: "#6f71be", displayDecimals: 4, description: "Projet blockchain majeur, capitalisation top 15, large adoption" },
    { slug: "rain", name: "Rain", symbol: "RAIN", type: "crypto", coingeckoId: "rain", finnhubSymbol: "BINANCE:RAINUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/69134/large/Rain_logo_1_.png?1762952191", fallbackColor: "#5599bf", displayDecimals: 4, description: "Projet blockchain majeur, capitalisation top 15, large adoption" },
    { slug: "usds", name: "USDS", symbol: "USDS", type: "crypto", coingeckoId: "usds", finnhubSymbol: "BINANCE:USDSUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683", fallbackColor: "#ea777f", displayDecimals: 4, description: "Projet blockchain majeur, capitalisation top 15, large adoption" },
    { slug: "leo-token", name: "LEO Token", symbol: "LEO", type: "crypto", coingeckoId: "leo-token", finnhubSymbol: "BINANCE:LEOUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607", fallbackColor: "#c9208b", displayDecimals: 2, description: "Projet blockchain majeur, capitalisation top 15, large adoption" },
    { slug: "zcash", name: "Zcash", symbol: "ZEC", type: "crypto", coingeckoId: "zcash", finnhubSymbol: "BINANCE:ZECUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/486/large/circle-zcash-color.png?1696501740", fallbackColor: "#e4fce6", displayDecimals: 2, description: "Projet blockchain majeur, capitalisation top 15, large adoption" },
    { slug: "lab", name: "LAB", symbol: "LAB", type: "crypto", coingeckoId: "lab", finnhubSymbol: "BINANCE:LABUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/70014/large/lab.png?1760352822", fallbackColor: "#f9664e", displayDecimals: 2, description: "Crypto majeure, capitalisation top 30, écosystème actif" },
    { slug: "monero", name: "Monero", symbol: "XMR", type: "crypto", coingeckoId: "monero", finnhubSymbol: "BINANCE:XMRUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460", fallbackColor: "#849b96", displayDecimals: 2, description: "Crypto majeure, capitalisation top 30, écosystème actif" },
    { slug: "stellar", name: "Stellar", symbol: "XLM", type: "crypto", coingeckoId: "stellar", finnhubSymbol: "BINANCE:XLMUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350", fallbackColor: "#67c752", displayDecimals: 4, description: "Crypto majeure, capitalisation top 30, écosystème actif" },
    { slug: "canton-network", name: "Canton", symbol: "CC", type: "crypto", coingeckoId: "canton-network", finnhubSymbol: "BINANCE:CCUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/70468/large/Canton-Ticker_%281%29.png?1762826299", fallbackColor: "#f17d45", displayDecimals: 4, description: "Crypto majeure, capitalisation top 30, écosystème actif" },
    { slug: "whitebit", name: "WhiteBIT Coin", symbol: "WBT", type: "crypto", coingeckoId: "whitebit", finnhubSymbol: "BINANCE:WBTUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096", fallbackColor: "#8785c2", displayDecimals: 2, description: "Crypto majeure, capitalisation top 30, écosystème actif" },
    { slug: "cardano", name: "Cardano", symbol: "ADA", type: "crypto", coingeckoId: "cardano", finnhubSymbol: "BINANCE:ADAUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090", fallbackColor: "#3684d4", displayDecimals: 4, description: "Crypto majeure, capitalisation top 30, écosystème actif" },
    { slug: "chainlink", name: "Chainlink", symbol: "LINK", type: "crypto", coingeckoId: "chainlink", finnhubSymbol: "BINANCE:LINKUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/877/large/Chainlink_Logo_500.png?1760023405", fallbackColor: "#c5a17a", displayDecimals: 2, description: "Crypto majeure, capitalisation top 30, écosystème actif" },
    { slug: "usd1-wlfi", name: "USD1", symbol: "USD1", type: "crypto", coingeckoId: "usd1-wlfi", finnhubSymbol: "BINANCE:USD1USDT", logoUrl: "https://coin-images.coingecko.com/coins/images/54977/large/USD1_1000x1000_transparent.png?1749297002", fallbackColor: "#3754fa", displayDecimals: 4, description: "Crypto majeure, capitalisation top 30, écosystème actif" },
    { slug: "dai", name: "Dai", symbol: "DAI", type: "crypto", coingeckoId: "dai", finnhubSymbol: "BINANCE:DAIUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/9956/large/Badge_Dai.png?1696509996", fallbackColor: "#9dbc4d", displayDecimals: 4, description: "Crypto majeure, capitalisation top 30, écosystème actif" },
    { slug: "ethena-usde", name: "Ethena USDe", symbol: "USDE", type: "crypto", coingeckoId: "ethena-usde", finnhubSymbol: "BINANCE:USDEUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/33613/large/usde.png?1733810059", fallbackColor: "#3b7ddd", displayDecimals: 4, description: "Crypto majeure, capitalisation top 30, écosystème actif" },
    { slug: "the-open-network", name: "Gram (prev. Toncoin)", symbol: "GRAM", type: "crypto", coingeckoId: "the-open-network", finnhubSymbol: "BINANCE:GRAMUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/17980/large/Gram_Circular_Badge.png?1781524778", fallbackColor: "#37efce", displayDecimals: 2, description: "Crypto majeure, capitalisation top 30, écosystème actif" },
    { slug: "bitcoin-cash", name: "Bitcoin Cash", symbol: "BCH", type: "crypto", coingeckoId: "bitcoin-cash", finnhubSymbol: "BINANCE:BCHUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932", fallbackColor: "#d7cd3c", displayDecimals: 2, description: "Crypto majeure, capitalisation top 30, écosystème actif" },
    { slug: "litecoin", name: "Litecoin", symbol: "LTC", type: "crypto", coingeckoId: "litecoin", finnhubSymbol: "BINANCE:LTCUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/2/large/litecoin.png?1696501400", fallbackColor: "#6f7b9d", displayDecimals: 2, description: "Crypto majeure, capitalisation top 30, écosystème actif" },
    { slug: "hashnote-usyc", name: "Circle USYC", symbol: "USYC", type: "crypto", coingeckoId: "hashnote-usyc", finnhubSymbol: "BINANCE:USYCUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/51054/large/Hashnote_SDYC_200x200.png?1730370965", fallbackColor: "#f1464a", displayDecimals: 2, description: "Crypto majeure, capitalisation top 30, écosystème actif" },
    { slug: "hedera-hashgraph", name: "Hedera", symbol: "HBAR", type: "crypto", coingeckoId: "hedera-hashgraph", finnhubSymbol: "BINANCE:HBARUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/3688/large/hbar.png?1696504364", fallbackColor: "#14ed6a", displayDecimals: 4, description: "Crypto majeure, capitalisation top 30, écosystème actif" },
    { slug: "global-dollar", name: "Global Dollar", symbol: "USDG", type: "crypto", coingeckoId: "global-dollar", finnhubSymbol: "BINANCE:USDGUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/51281/large/GDN_USDG_Token_200x200.png?1730484111", fallbackColor: "#9d6a76", displayDecimals: 4, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "avalanche-2", name: "Avalanche", symbol: "AVAX", type: "crypto", coingeckoId: "avalanche-2", finnhubSymbol: "BINANCE:AVAXUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png?1696512369", fallbackColor: "#34e16f", displayDecimals: 2, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "sui", name: "Sui", symbol: "SUI", type: "crypto", coingeckoId: "sui", finnhubSymbol: "BINANCE:SUIUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/26375/large/sui-ocean-square.png?1727791290", fallbackColor: "#71d142", displayDecimals: 4, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "paypal-usd", name: "PayPal USD", symbol: "PYUSD", type: "crypto", coingeckoId: "paypal-usd", finnhubSymbol: "BINANCE:PYUSDUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/31212/large/PYUSD_Token_Logo_2x.png?1765987788", fallbackColor: "#e58fe3", displayDecimals: 4, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "crypto-com-chain", name: "Cronos", symbol: "CRO", type: "crypto", coingeckoId: "crypto-com-chain", finnhubSymbol: "BINANCE:CROUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/7310/large/cro_token_logo.png?1696507599", fallbackColor: "#7d41d6", displayDecimals: 4, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "shiba-inu", name: "Shiba Inu", symbol: "SHIB", type: "crypto", coingeckoId: "shiba-inu", finnhubSymbol: "BINANCE:SHIBUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/11939/large/shiba.png?1696511800", fallbackColor: "#5aa39a", displayDecimals: 8, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "tether-gold", name: "Tether Gold", symbol: "XAUT", type: "crypto", coingeckoId: "tether-gold", finnhubSymbol: "BINANCE:XAUTUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/10481/large/logo.png?1774627372", fallbackColor: "#f7fcc1", displayDecimals: 2, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "near", name: "NEAR Protocol", symbol: "NEAR", type: "crypto", coingeckoId: "near", finnhubSymbol: "BINANCE:NEARUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/10365/large/near.jpg?1696510367", fallbackColor: "#85f06c", displayDecimals: 2, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "blackrock-usd-institutional-digital-liquidity-fund", name: "BlackRock USD Institutional Digital Liquidity Fund", symbol: "BUIDL", type: "crypto", coingeckoId: "blackrock-usd-institutional-digital-liquidity-fund", finnhubSymbol: "BINANCE:BUIDLUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/36291/large/blackrock.png?1711013223", fallbackColor: "#f36bae", displayDecimals: 2, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "ondo-us-dollar-yield", name: "Ondo US Dollar Yield", symbol: "USDY", type: "crypto", coingeckoId: "ondo-us-dollar-yield", finnhubSymbol: "BINANCE:USDYUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/31700/large/usdy_%281%29.png?1696530524", fallbackColor: "#2dc59a", displayDecimals: 2, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "bittensor", name: "Bittensor", symbol: "TAO", type: "crypto", coingeckoId: "bittensor", finnhubSymbol: "BINANCE:TAOUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/28452/large/ARUsPeNQ_400x400.jpeg?1696527447", fallbackColor: "#cf85f3", displayDecimals: 2, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "world-liberty-financial", name: "World Liberty Financial", symbol: "WLFI", type: "crypto", coingeckoId: "world-liberty-financial", finnhubSymbol: "BINANCE:WLFIUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/50767/large/wlfi.png?1756438915", fallbackColor: "#28c5cb", displayDecimals: 4, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "pax-gold", name: "PAX Gold", symbol: "PAXG", type: "crypto", coingeckoId: "pax-gold", finnhubSymbol: "BINANCE:PAXGUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/9519/large/paxgold.png?1696509604", fallbackColor: "#8638ee", displayDecimals: 2, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "uniswap", name: "Uniswap", symbol: "UNI", type: "crypto", coingeckoId: "uniswap", finnhubSymbol: "BINANCE:UNIUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/12504/large/uniswap-logo.png?1720676669", fallbackColor: "#bc4290", displayDecimals: 2, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "aster-2", name: "Aster", symbol: "ASTER", type: "crypto", coingeckoId: "aster-2", finnhubSymbol: "BINANCE:ASTERUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/69040/large/_ASTER.png?1757326782", fallbackColor: "#868ed6", displayDecimals: 4, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "worldcoin-wld", name: "Worldcoin", symbol: "WLD", type: "crypto", coingeckoId: "worldcoin-wld", finnhubSymbol: "BINANCE:WLDUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/31069/large/worldcoin.jpeg?1696529903", fallbackColor: "#86d489", displayDecimals: 4, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "okb", name: "OKB", symbol: "OKB", type: "crypto", coingeckoId: "okb", finnhubSymbol: "BINANCE:OKBUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/4463/large/WeChat_Image_20220118095654.png?1696505053", fallbackColor: "#c993c4", displayDecimals: 2, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "ripple-usd", name: "Ripple USD", symbol: "RLUSD", type: "crypto", coingeckoId: "ripple-usd", finnhubSymbol: "BINANCE:RLUSDUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/39651/large/RLUSD_200x200_%281%29.png?1727376633", fallbackColor: "#eec788", displayDecimals: 2, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "ondo-finance", name: "Ondo", symbol: "ONDO", type: "crypto", coingeckoId: "ondo-finance", finnhubSymbol: "BINANCE:ONDOUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/26580/large/ONDO.png?1696525656", fallbackColor: "#26adfb", displayDecimals: 4, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "htx-dao", name: "HTX DAO", symbol: "HTX", type: "crypto", coingeckoId: "htx-dao", finnhubSymbol: "BINANCE:HTXUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/35491/large/Frame_1321318576.png?1708908626", fallbackColor: "#9041bb", displayDecimals: 8, description: "Projet crypto établi, top 50 CoinGecko par capitalisation" },
    { slug: "mantle", name: "Mantle", symbol: "MNT", type: "crypto", coingeckoId: "mantle", finnhubSymbol: "BINANCE:MNTUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/30980/large/MNT_Token_Logo.png?1765516974", fallbackColor: "#f8aef6", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "aave", name: "Aave", symbol: "AAVE", type: "crypto", coingeckoId: "aave", finnhubSymbol: "BINANCE:AAVEUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/12645/large/aave-token-round.png?1720472354", fallbackColor: "#08d9ac", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "polkadot", name: "Polkadot", symbol: "DOT", type: "crypto", coingeckoId: "polkadot", finnhubSymbol: "BINANCE:DOTUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/12171/large/polkadot.jpg?1766533446", fallbackColor: "#4554e0", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "falcon-finance", name: "Falcon USD", symbol: "USDF", type: "crypto", coingeckoId: "falcon-finance", finnhubSymbol: "BINANCE:USDFUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/54558/large/ff_200_X_200.png?1740741076", fallbackColor: "#f07917", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "pi-network", name: "Pi Network", symbol: "PI", type: "crypto", coingeckoId: "pi-network", finnhubSymbol: "BINANCE:PIUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/54342/large/pi_network.jpg?1739347576", fallbackColor: "#4ad481", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "usdd", name: "USDD", symbol: "USDD", type: "crypto", coingeckoId: "usdd", finnhubSymbol: "BINANCE:USDDUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/25380/large/UUSD.jpg?1696524513", fallbackColor: "#f1ca02", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "bfusd", name: "BFUSD", symbol: "BFUSD", type: "crypto", coingeckoId: "bfusd", finnhubSymbol: "BINANCE:BFUSDUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/68227/large/bfusd.png?1755132827", fallbackColor: "#9d86d7", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "internet-computer", name: "Internet Computer", symbol: "ICP", type: "crypto", coingeckoId: "internet-computer", finnhubSymbol: "BINANCE:ICPUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/14495/large/Internet_Computer_logo.png?1696514180", fallbackColor: "#508ac5", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "sky", name: "Sky", symbol: "SKY", type: "crypto", coingeckoId: "sky", finnhubSymbol: "BINANCE:SKYUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/39925/large/sky.jpg?1724827980", fallbackColor: "#a924e1", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "morpho", name: "Morpho", symbol: "MORPHO", type: "crypto", coingeckoId: "morpho", finnhubSymbol: "BINANCE:MORPHOUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/29837/large/Morpho-token-icon.png?1726771230", fallbackColor: "#dc4f53", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "bitget-token", name: "Bitget Token", symbol: "BGB", type: "crypto", coingeckoId: "bitget-token", finnhubSymbol: "BINANCE:BGBUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/11610/large/Bitget_logo.png?1736925727", fallbackColor: "#f31d68", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "ethereum-classic", name: "Ethereum Classic", symbol: "ETC", type: "crypto", coingeckoId: "ethereum-classic", finnhubSymbol: "BINANCE:ETCUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/453/large/ethereum-classic-logo.png?1696501717", fallbackColor: "#936dfe", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "united-stables", name: "United Stables", symbol: "U", type: "crypto", coingeckoId: "united-stables", finnhubSymbol: "BINANCE:UUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/71157/large/united-stables-logo.jpg?1766061640", fallbackColor: "#7d9395", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "pepe", name: "Pepe", symbol: "PEPE", type: "crypto", coingeckoId: "pepe", finnhubSymbol: "BINANCE:PEPEUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/29850/large/pepe-token.jpeg?1696528776", fallbackColor: "#ab8740", displayDecimals: 8, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "dexe", name: "DeXe", symbol: "DEXE", type: "crypto", coingeckoId: "dexe", finnhubSymbol: "BINANCE:DEXEUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/12713/large/DEXE_token_logo.png?1696512514", fallbackColor: "#29dbb3", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "quant-network", name: "Quant", symbol: "QNT", type: "crypto", coingeckoId: "quant-network", finnhubSymbol: "BINANCE:QNTUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/3370/large/5ZOu7brX_400x400.jpg?1696504070", fallbackColor: "#f0bd8b", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "blockchain-capital", name: "Blockchain Capital", symbol: "BCAP", type: "crypto", coingeckoId: "blockchain-capital", finnhubSymbol: "BINANCE:BCAPUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/56040/large/bcap_logo_200.png?1748088291", fallbackColor: "#92868d", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "memecore", name: "MemeCore", symbol: "M", type: "crypto", coingeckoId: "memecore", finnhubSymbol: "BINANCE:MUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/53247/large/square-bg-transparent.png?1752637478", fallbackColor: "#7d867f", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "eutbl", name: "Spiko EU T-Bills Money Market Fund", symbol: "EUTBL", type: "crypto", coingeckoId: "eutbl", finnhubSymbol: "BINANCE:EUTBLUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/39657/large/EUTBL.png?1723517425", fallbackColor: "#27ecec", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "kucoin-shares", name: "KuCoin", symbol: "KCS", type: "crypto", coingeckoId: "kucoin-shares", finnhubSymbol: "BINANCE:KCSUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/1047/large/sa9z79.png?1696502152", fallbackColor: "#e327f8", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "stable-2", name: "​​Stable", symbol: "STABLE", type: "crypto", coingeckoId: "stable-2", finnhubSymbol: "BINANCE:STABLEUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/69242/large/stable-logotype-framed-square-light.png?1762753913", fallbackColor: "#1f5ff9", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "janus-henderson-anemoy-treasury-fund", name: "Janus Henderson Anemoy Treasury Fund", symbol: "JTRSY", type: "crypto", coingeckoId: "janus-henderson-anemoy-treasury-fund", finnhubSymbol: "BINANCE:JTRSYUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/70445/large/JTRSY.png?1762078582", fallbackColor: "#719b96", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "usdgo", name: "USDGO", symbol: "USDGO", type: "crypto", coingeckoId: "usdgo", finnhubSymbol: "BINANCE:USDGOUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/102172077/large/USDGO_%287%29.png?1771437018", fallbackColor: "#7754c9", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "render-token", name: "Render", symbol: "RENDER", type: "crypto", coingeckoId: "render-token", finnhubSymbol: "BINANCE:RENDERUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/11636/large/rndr.png?1696511529", fallbackColor: "#ce687b", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "cosmos", name: "Cosmos Hub", symbol: "ATOM", type: "crypto", coingeckoId: "cosmos", finnhubSymbol: "BINANCE:ATOMUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/1481/large/cosmos_hub.png?1696502525", fallbackColor: "#3989da", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "kaspa", name: "Kaspa", symbol: "KAS", type: "crypto", coingeckoId: "kaspa", finnhubSymbol: "BINANCE:KASUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/25751/large/kaspa-icon-exchanges.png?1696524837", fallbackColor: "#efe520", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "superstate-short-duration-us-government-securities-fund-ustb", name: "Invesco Short Duration US Government Securities Fund", symbol: "USTB", type: "crypto", coingeckoId: "superstate-short-duration-us-government-securities-fund-ustb", finnhubSymbol: "BINANCE:USTBUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/35012/large/Invesco_icon_lg.png?1780816895", fallbackColor: "#efced9", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "jupiter-exchange-solana", name: "Jupiter", symbol: "JUP", type: "crypto", coingeckoId: "jupiter-exchange-solana", finnhubSymbol: "BINANCE:JUPUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/34188/large/jup.png?1704266489", fallbackColor: "#65c747", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "polygon-ecosystem-token", name: "POL (ex-MATIC)", symbol: "POL", type: "crypto", coingeckoId: "polygon-ecosystem-token", finnhubSymbol: "BINANCE:POLUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/32440/large/pol.png?1759114181", fallbackColor: "#6654ca", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "algorand", name: "Algorand", symbol: "ALGO", type: "crypto", coingeckoId: "algorand", finnhubSymbol: "BINANCE:ALGOUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/4380/large/download.png?1696504978", fallbackColor: "#c240a2", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "usdtb", name: "USDtb", symbol: "USDTB", type: "crypto", coingeckoId: "usdtb", finnhubSymbol: "BINANCE:USDTBUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/52804/large/76357aa8-4ef7-446c-bad3-a3f944eeec7a.jpeg?1758277468", fallbackColor: "#4f68d1", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "ethena", name: "Ethena", symbol: "ENA", type: "crypto", coingeckoId: "ethena", finnhubSymbol: "BINANCE:ENAUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/36530/large/ethena.png?1711701436", fallbackColor: "#3fe589", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "bianrensheng", name: "币安人生 (BinanceLife)", symbol: "币安人生", type: "crypto", coingeckoId: "bianrensheng", finnhubSymbol: "BINANCE:币安人生USDT", logoUrl: "https://coin-images.coingecko.com/coins/images/69848/large/%E5%B8%81%E5%AE%89%E4%BA%BA%E7%94%9F.png?1759839225", fallbackColor: "#c12e87", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "nexo", name: "NEXO", symbol: "NEXO", type: "crypto", coingeckoId: "nexo", finnhubSymbol: "BINANCE:NEXOUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/3695/large/CG-nexo-token-200x200_2x.png?1730414360", fallbackColor: "#b325f1", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "audiera", name: "Audiera", symbol: "BEAT", type: "crypto", coingeckoId: "audiera", finnhubSymbol: "BINANCE:BEATUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/70428/large/audiera.png?1761964064", fallbackColor: "#7dd5a2", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "beldex", name: "Beldex", symbol: "BDX", type: "crypto", coingeckoId: "beldex", finnhubSymbol: "BINANCE:BDXUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/5111/large/Beldex.png?1696505631", fallbackColor: "#fac9f9", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "just", name: "JUST", symbol: "JST", type: "crypto", coingeckoId: "just", finnhubSymbol: "BINANCE:JSTUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/11095/large/JUST.jpg?1696511035", fallbackColor: "#8134b8", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "gatechain-token", name: "Gate", symbol: "GT", type: "crypto", coingeckoId: "gatechain-token", finnhubSymbol: "BINANCE:GTUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/8183/large/200X200.png?1735246724", fallbackColor: "#9df9f8", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "janus-henderson-anemoy-aaa-clo-fund", name: "Janus Henderson Anemoy AAA CLO Fund", symbol: "JAAA", type: "crypto", coingeckoId: "janus-henderson-anemoy-aaa-clo-fund", finnhubSymbol: "BINANCE:JAAAUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/70446/large/jaaa.png?1762078666", fallbackColor: "#f55f1a", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "venice-token", name: "Venice Token", symbol: "VVV", type: "crypto", coingeckoId: "venice-token", finnhubSymbol: "BINANCE:VVVUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/54023/large/VVV_Token_Transparent.png?1741856877", fallbackColor: "#5c64d5", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "spiko-amundi-overnight-swap-fund-eur", name: "Spiko Amundi Overnight Swap Fund (EUR)", symbol: "EURSAFO", type: "crypto", coingeckoId: "spiko-amundi-overnight-swap-fund-eur", finnhubSymbol: "BINANCE:EURSAFOUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/102172591/large/Fund_eurSAF0.png?1774104814", fallbackColor: "#9bd9e0", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "adi-token", name: "ADI", symbol: "ADI", type: "crypto", coingeckoId: "adi-token", finnhubSymbol: "BINANCE:ADIUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/68846/large/ADI_Token-min.png?1765296433", fallbackColor: "#9fb759", displayDecimals: 2, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "gho", name: "GHO", symbol: "GHO", type: "crypto", coingeckoId: "gho", finnhubSymbol: "BINANCE:GHOUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/30663/large/gho-token-logo.png?1720517092", fallbackColor: "#2a8ab4", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "flare-networks", name: "Flare", symbol: "FLR", type: "crypto", coingeckoId: "flare-networks", finnhubSymbol: "BINANCE:FLRUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/28624/large/FLR-icon200x200.png?1696527609", fallbackColor: "#377cc7", displayDecimals: 6, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "filecoin", name: "Filecoin", symbol: "FIL", type: "crypto", coingeckoId: "filecoin", finnhubSymbol: "BINANCE:FILUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/12817/large/filecoin.png?1696512609", fallbackColor: "#8d40ef", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "ylds", name: "YLDS", symbol: "YLDS", type: "crypto", coingeckoId: "ylds", finnhubSymbol: "BINANCE:YLDSUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/66486/large/YLDS.png?1772560579", fallbackColor: "#c3cc09", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "xdce-crowd-sale", name: "XDC Network", symbol: "XDC", type: "crypto", coingeckoId: "xdce-crowd-sale", finnhubSymbol: "BINANCE:XDCUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/2912/large/xdc-icon.png?1696503661", fallbackColor: "#ff3b51", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "usual-usd", name: "Usual USD", symbol: "USD0", type: "crypto", coingeckoId: "usual-usd", finnhubSymbol: "BINANCE:USD0USDT", logoUrl: "https://coin-images.coingecko.com/coins/images/38272/large/USD0LOGO.png?1716962811", fallbackColor: "#a3a441", displayDecimals: 4, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "pump-fun", name: "Pump.fun", symbol: "PUMP", type: "crypto", coingeckoId: "pump-fun", finnhubSymbol: "BINANCE:PUMPUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/67164/large/pump.jpg?1751949376", fallbackColor: "#38db56", displayDecimals: 6, description: "Token crypto figurant dans le top 100 CoinGecko" },
    { slug: "hash-2", name: "Provenance Blockchain", symbol: "HASH", type: "crypto", coingeckoId: "hash-2", finnhubSymbol: "BINANCE:HASHUSDT", logoUrl: "https://coin-images.coingecko.com/coins/images/66154/large/Hastra_Icon.png?1748497203", fallbackColor: "#0cb7f5", displayDecimals: 6, description: "Token crypto figurant dans le top 100 CoinGecko" },
];

const forex: AssetMeta[] = [
    { slug: "eurusd", name: "EUR/USD", symbol: "EUR/USD", type: "forex", finnhubSymbol: "OANDA:EUR_USD", logoUrl: "https://logo.clearbit.com/ecb.europa.eu", fallbackColor: "#003399", displayDecimals: 5, description: "Euro contre dollar US, paire la plus liquide au monde" },
    { slug: "gbpusd", name: "GBP/USD", symbol: "GBP/USD", type: "forex", finnhubSymbol: "OANDA:GBP_USD", logoUrl: "https://logo.clearbit.com/bankofengland.co.uk", fallbackColor: "#012169", displayDecimals: 5, description: "Livre sterling contre dollar US, paire majeure" },
    { slug: "usdjpy", name: "USD/JPY", symbol: "USD/JPY", type: "forex", finnhubSymbol: "OANDA:USD_JPY", logoUrl: "https://logo.clearbit.com/boj.or.jp", fallbackColor: "#BC002D", displayDecimals: 3, description: "Dollar US contre yen japonais, paire Asie dominante" },
    { slug: "usdcad", name: "USD/CAD", symbol: "USD/CAD", type: "forex", finnhubSymbol: "OANDA:USD_CAD", logoUrl: "https://logo.clearbit.com/bankofcanada.ca", fallbackColor: "#FF0000", displayDecimals: 5, description: "Dollar US contre dollar canadien, paire commodity" },
    { slug: "usdchf", name: "USD/CHF", symbol: "USD/CHF", type: "forex", finnhubSymbol: "OANDA:USD_CHF", logoUrl: "https://logo.clearbit.com/snb.ch", fallbackColor: "#D52B1E", displayDecimals: 5, description: "Dollar US contre franc suisse, valeur refuge" },
    { slug: "audusd", name: "AUD/USD", symbol: "AUD/USD", type: "forex", finnhubSymbol: "OANDA:AUD_USD", logoUrl: "https://logo.clearbit.com/rba.gov.au", fallbackColor: "#004B93", displayDecimals: 5, description: "Dollar australien contre dollar US, paire commodity" },
    { slug: "eurgbp", name: "EUR/GBP", symbol: "EUR/GBP", type: "forex", finnhubSymbol: "OANDA:EUR_GBP", logoUrl: "https://logo.clearbit.com/ecb.europa.eu", fallbackColor: "#003399", displayDecimals: 5, description: "Euro contre livre sterling, paire cross majeure" },
    { slug: "eurjpy", name: "EUR/JPY", symbol: "EUR/JPY", type: "forex", finnhubSymbol: "OANDA:EUR_JPY", logoUrl: "https://logo.clearbit.com/ecb.europa.eu", fallbackColor: "#BC002D", displayDecimals: 3, description: "Euro contre yen japonais, paire cross liquide" },
    { slug: "nzdusd", name: "NZD/USD", symbol: "NZD/USD", type: "forex", finnhubSymbol: "OANDA:NZD_USD", logoUrl: "https://logo.clearbit.com/rbnz.govt.nz", fallbackColor: "#003366", displayDecimals: 5, description: "Dollar néo-zélandais contre dollar US, paire commodity" },
    { slug: "usdsgd", name: "USD/SGD", symbol: "USD/SGD", type: "forex", finnhubSymbol: "OANDA:USD_SGD", logoUrl: "https://logo.clearbit.com/mas.gov.sg", fallbackColor: "#C00", displayDecimals: 4, description: "Dollar US contre dollar singapourien, paire Asie" },
];

const commodities: AssetMeta[] = [
    { slug: "gold", name: "Gold", symbol: "XAU", type: "commodity", finnhubSymbol: "OANDA:XAU_USD", logoUrl: "https://logo.clearbit.com/gold.org", fallbackColor: "#FFD700", displayDecimals: 2, description: "Métal précieux, valeur refuge ultime" },
    { slug: "silver", name: "Silver", symbol: "XAG", type: "commodity", finnhubSymbol: "OANDA:XAG_USD", logoUrl: "https://logo.clearbit.com/silverinstitute.org", fallbackColor: "#C0C0C0", displayDecimals: 3, description: "Métal précieux industriel et refuge" },
    { slug: "crude-oil-wti", name: "Crude Oil WTI", symbol: "WTI", type: "commodity", finnhubSymbol: "NYMEX:CL1!", logoUrl: "https://logo.clearbit.com/eia.gov", fallbackColor: "#8B4513", displayDecimals: 2, description: "Pétrole brut WTI, référence US" },
    { slug: "brent", name: "Brent Crude", symbol: "BRENT", type: "commodity", finnhubSymbol: "ICE:B1!", logoUrl: "https://logo.clearbit.com/ice.com", fallbackColor: "#000", displayDecimals: 2, description: "Pétrole brut Brent, référence Europe" },
    { slug: "natural-gas", name: "Natural Gas", symbol: "NG", type: "commodity", finnhubSymbol: "NYMEX:NG1!", logoUrl: "https://logo.clearbit.com/eia.gov", fallbackColor: "#4682B4", displayDecimals: 3, description: "Gaz naturel, indicateur énergétique clé" },
    { slug: "copper", name: "Copper", symbol: "HG", type: "commodity", finnhubSymbol: "NYMEX:HG1!", logoUrl: "https://logo.clearbit.com/lme.com", fallbackColor: "#B87333", displayDecimals: 4, description: "Cuivre, baromètre de l'économie mondiale" },
    { slug: "platinum", name: "Platinum", symbol: "PL", type: "commodity", finnhubSymbol: "NYMEX:PL1!", logoUrl: "https://logo.clearbit.com/lme.com", fallbackColor: "#E5E4E2", displayDecimals: 2, description: "Platine, métal précieux industriel" },
];

const indices: AssetMeta[] = [
    { slug: "spx", name: "S&P 500", symbol: "SPX", type: "index", finnhubSymbol: "INDEX:SPX", logoUrl: "https://logo.clearbit.com/spglobal.com", fallbackColor: "#003B71", displayDecimals: 2, description: "500 plus grandes capitalisations américaines" },
    { slug: "ndx", name: "Nasdaq 100", symbol: "NDX", type: "index", finnhubSymbol: "INDEX:NDX", logoUrl: "https://logo.clearbit.com/nasdaq.com", fallbackColor: "#000", displayDecimals: 2, description: "100 plus grandes non-financières du Nasdaq" },
    { slug: "dax", name: "DAX 40", symbol: "DAX", type: "index", finnhubSymbol: "INDEX:DAX", logoUrl: "https://logo.clearbit.com/dax-indices.com", fallbackColor: "#000", displayDecimals: 2, description: "40 plus grandes capitalisations allemandes" },
    { slug: "ftse", name: "FTSE 100", symbol: "FTSE", type: "index", finnhubSymbol: "INDEX:FTSE", logoUrl: "https://logo.clearbit.com/ftserussell.com", fallbackColor: "#0F2041", displayDecimals: 2, description: "100 plus grandes capitalisations britanniques" },
    { slug: "cac40", name: "CAC 40", symbol: "CAC", type: "index", finnhubSymbol: "INDEX:CAC", logoUrl: "https://logo.clearbit.com/euronext.com", fallbackColor: "#002395", displayDecimals: 2, description: "40 plus grandes capitalisations françaises" },
    { slug: "nikkei", name: "Nikkei 225", symbol: "N225", type: "index", finnhubSymbol: "INDEX:N225", logoUrl: "https://logo.clearbit.com/jpx.co.jp", fallbackColor: "#000", displayDecimals: 2, description: "225 plus grandes capitalisations japonaises" },
    { slug: "hang-seng", name: "Hang Seng", symbol: "HSI", type: "index", finnhubSymbol: "INDEX:HSI", logoUrl: "https://logo.clearbit.com/hkex.com.hk", fallbackColor: "#DE2910", displayDecimals: 2, description: "Plus grandes capitalisations Hong Kong" },
    { slug: "shanghai", name: "Shanghai Composite", symbol: "SSEC", type: "index", finnhubSymbol: "INDEX:SHCOMP", logoUrl: "https://logo.clearbit.com/sse.com.cn", fallbackColor: "#EE1C25", displayDecimals: 2, description: "Bourse de Shanghai" },
    { slug: "dow-jones", name: "Dow Jones", symbol: "DJI", type: "index", finnhubSymbol: "INDEX:DJI", logoUrl: "https://logo.clearbit.com/spglobal.com", fallbackColor: "#003B71", displayDecimals: 2, description: "30 plus grandes capitalisations industrielles US" },
    { slug: "russell-2000", name: "Russell 2000", symbol: "RUT", type: "index", finnhubSymbol: "INDEX:RUT", logoUrl: "https://logo.clearbit.com/ftserussell.com", fallbackColor: "#003B71", displayDecimals: 2, description: "2000 plus petites capitalisations US" },
    { slug: "vix", name: "VIX", symbol: "VIX", type: "index", finnhubSymbol: "INDEX:VIX", logoUrl: "https://logo.clearbit.com/cboe.com", fallbackColor: "#00FF00", displayDecimals: 2, description: "Indice de volatilité CBOE, fear gauge" },
];

const stocks: AssetMeta[] = [
    { slug: "aapl", name: "Apple Inc.", symbol: "AAPL", type: "stock", finnhubSymbol: "AAPL", logoUrl: "https://logo.clearbit.com/apple.com", fallbackColor: "#555", displayDecimals: 2, description: "Leader tech US, iPhone, Mac, Services" },
    { slug: "msft", name: "Microsoft Corp.", symbol: "MSFT", type: "stock", finnhubSymbol: "MSFT", logoUrl: "https://logo.clearbit.com/microsoft.com", fallbackColor: "#00A4EF", displayDecimals: 2, description: "Géant du logiciel, Azure, Cloud, AI" },
    { slug: "googl", name: "Alphabet Inc. C", symbol: "GOOGL", type: "stock", finnhubSymbol: "GOOGL", logoUrl: "https://logo.clearbit.com/abc.xyz", fallbackColor: "#4285F4", displayDecimals: 2, description: "Google, YouTube, Cloud, AI/DeepMind" },
    { slug: "amzn", name: "Amazon.com Inc.", symbol: "AMZN", type: "stock", finnhubSymbol: "AMZN", logoUrl: "https://logo.clearbit.com/amazon.com", fallbackColor: "#FF9900", displayDecimals: 2, description: "E-commerce, AWS Cloud, Prime, AI" },
    { slug: "tsla", name: "Tesla Inc.", symbol: "TSLA", type: "stock", finnhubSymbol: "TSLA", logoUrl: "https://logo.clearbit.com/tesla.com", fallbackColor: "#E82127", displayDecimals: 2, description: "Véhicules électriques, énergie, robotique" },
    { slug: "nvda", name: "NVIDIA Corp.", symbol: "NVDA", type: "stock", finnhubSymbol: "NVDA", logoUrl: "https://logo.clearbit.com/nvidia.com", fallbackColor: "#76B900", displayDecimals: 2, description: "Leader GPU, AI/HPC, gaming, datacenter" },
    { slug: "meta", name: "Meta Platforms", symbol: "META", type: "stock", finnhubSymbol: "META", logoUrl: "https://logo.clearbit.com/meta.com", fallbackColor: "#1877F2", displayDecimals: 2, description: "Facebook, Instagram, WhatsApp, Reality Labs" },
    { slug: "brk-b", name: "Berkshire Hathaway B", symbol: "BRK.B", type: "stock", finnhubSymbol: "BRK.B", logoUrl: "https://logo.clearbit.com/berkshirehathaway.com", fallbackColor: "#000", displayDecimals: 2, description: "Conglomérat d'investissement de Warren Buffett" },
    { slug: "lly", name: "Eli Lilly & Co.", symbol: "LLY", type: "stock", finnhubSymbol: "LLY", logoUrl: "https://logo.clearbit.com/lilly.com", fallbackColor: "#006", displayDecimals: 2, description: "Leader pharmaceutique, traitements innovants" },
    { slug: "v", name: "Visa Inc.", symbol: "V", type: "stock", finnhubSymbol: "V", logoUrl: "https://logo.clearbit.com/visa.com", fallbackColor: "#1A1F71", displayDecimals: 2, description: "Leader mondial des paiements électroniques" },
    { slug: "jpm", name: "JPMorgan Chase", symbol: "JPM", type: "stock", finnhubSymbol: "JPM", logoUrl: "https://logo.clearbit.com/jpmorganchase.com", fallbackColor: "#003", displayDecimals: 2, description: "Plus grande banque américaine" },
    { slug: "xom", name: "Exxon Mobil Corp.", symbol: "XOM", type: "stock", finnhubSymbol: "XOM", logoUrl: "https://logo.clearbit.com/exxonmobil.com", fallbackColor: "#D50032", displayDecimals: 2, description: "Leader pétrolier intégré US" },
    { slug: "wmt", name: "Walmart Inc.", symbol: "WMT", type: "stock", finnhubSymbol: "WMT", logoUrl: "https://logo.clearbit.com/walmart.com", fallbackColor: "#0071CE", displayDecimals: 2, description: "Plus grand retailer mondial" },
    { slug: "jnj", name: "Johnson & Johnson", symbol: "JNJ", type: "stock", finnhubSymbol: "JNJ", logoUrl: "https://logo.clearbit.com/jnj.com", fallbackColor: "#D50032", displayDecimals: 2, description: "Leader santé, pharma et dispositifs médicaux" },
    { slug: "ma", name: "Mastercard Inc.", symbol: "MA", type: "stock", finnhubSymbol: "MA", logoUrl: "https://logo.clearbit.com/mastercard.com", fallbackColor: "#EB001B", displayDecimals: 2, description: "Réseau de paiement global" },
    { slug: "pg", name: "Procter & Gamble", symbol: "PG", type: "stock", finnhubSymbol: "PG", logoUrl: "https://logo.clearbit.com/pg.com", fallbackColor: "#003DA5", displayDecimals: 2, description: "Leader biens de consommation courante" },
    { slug: "hd", name: "Home Depot Inc.", symbol: "HD", type: "stock", finnhubSymbol: "HD", logoUrl: "https://logo.clearbit.com/homedepot.com", fallbackColor: "#F96302", displayDecimals: 2, description: "Plus grand retailer de bricolage US" },
    { slug: "cvx", name: "Chevron Corp.", symbol: "CVX", type: "stock", finnhubSymbol: "CVX", logoUrl: "https://logo.clearbit.com/chevron.com", fallbackColor: "#D50032", displayDecimals: 2, description: "Major pétrolière intégrée US" },
    { slug: "mrk", name: "Merck & Co.", symbol: "MRK", type: "stock", finnhubSymbol: "MRK", logoUrl: "https://logo.clearbit.com/merck.com", fallbackColor: "#008", displayDecimals: 2, description: "Géant pharmaceutique US" },
    { slug: "abbv", name: "AbbVie Inc.", symbol: "ABBV", type: "stock", finnhubSymbol: "ABBV", logoUrl: "https://logo.clearbit.com/abbvie.com", fallbackColor: "#073", displayDecimals: 2, description: "BioPharma leader, immunologie, oncologie" },
    { slug: "pep", name: "PepsiCo Inc.", symbol: "PEP", type: "stock", finnhubSymbol: "PEP", logoUrl: "https://logo.clearbit.com/pepsico.com", fallbackColor: "#004B93", displayDecimals: 2, description: "Leader boissons & snacks mondial" },
    { slug: "ko", name: "Coca-Cola Co.", symbol: "KO", type: "stock", finnhubSymbol: "KO", logoUrl: "https://logo.clearbit.com/coca-cola.com", fallbackColor: "#F40009", displayDecimals: 2, description: "Leader boissons non-alcoolisées mondial" },
    { slug: "bac", name: "Bank of America", symbol: "BAC", type: "stock", finnhubSymbol: "BAC", logoUrl: "https://logo.clearbit.com/bankofamerica.com", fallbackColor: "#012169", displayDecimals: 2, description: "Banque américaine majeure" },
    { slug: "pfe", name: "Pfizer Inc.", symbol: "PFE", type: "stock", finnhubSymbol: "PFE", logoUrl: "https://logo.clearbit.com/pfizer.com", fallbackColor: "#D50032", displayDecimals: 2, description: "Leader pharmaceutique global" },
    { slug: "cost", name: "Costco Wholesale", symbol: "COST", type: "stock", finnhubSymbol: "COST", logoUrl: "https://logo.clearbit.com/costco.com", fallbackColor: "#005CAA", displayDecimals: 2, description: "Leader du retail entrepôt, adhésion" },
    { slug: "tmo", name: "Thermo Fisher Scientific", symbol: "TMO", type: "stock", finnhubSymbol: "TMO", logoUrl: "https://logo.clearbit.com/thermofisher.com", fallbackColor: "#00A1DF", displayDecimals: 2, description: "Leader équipements scientifiques" },
    { slug: "mcd", name: "McDonald's Corp.", symbol: "MCD", type: "stock", finnhubSymbol: "MCD", logoUrl: "https://logo.clearbit.com/mcdonalds.com", fallbackColor: "#DA291C", displayDecimals: 2, description: "Leader restauration rapide mondial" },
    { slug: "crm", name: "Salesforce Inc.", symbol: "CRM", type: "stock", finnhubSymbol: "CRM", logoUrl: "https://logo.clearbit.com/salesforce.com", fallbackColor: "#00A1E0", displayDecimals: 2, description: "Leader CRM Cloud/SaaS" },
    { slug: "acn", name: "Accenture PLC", symbol: "ACN", type: "stock", finnhubSymbol: "ACN", logoUrl: "https://logo.clearbit.com/accenture.com", fallbackColor: "#A100FF", displayDecimals: 2, description: "Leader conseil & services IT global" },
    { slug: "abt", name: "Abbott Laboratories", symbol: "ABT", type: "stock", finnhubSymbol: "ABT", logoUrl: "https://logo.clearbit.com/abbott.com", fallbackColor: "#029", displayDecimals: 2, description: "Leader santé, diagnostics, dispositifs" },
];

const etfs: AssetMeta[] = [
    { slug: "spy", name: "SPDR S&P 500 ETF", symbol: "SPY", type: "etf", finnhubSymbol: "SPY", logoUrl: "https://logo.clearbit.com/spdrs.com", fallbackColor: "#003B71", displayDecimals: 2, description: "ETF S&P 500 le plus liquide au monde" },
    { slug: "qqq", name: "Invesco QQQ Trust", symbol: "QQQ", type: "etf", finnhubSymbol: "QQQ", logoUrl: "https://logo.clearbit.com/invesco.com", fallbackColor: "#000", displayDecimals: 2, description: "ETF Nasdaq 100, tech-intensive" },
    { slug: "voo", name: "Vanguard S&P 500 ETF", symbol: "VOO", type: "etf", finnhubSymbol: "VOO", logoUrl: "https://logo.clearbit.com/vanguard.com", fallbackColor: "#00A4EF", displayDecimals: 2, description: "ETF S&P 500, frais les plus bas" },
    { slug: "ivv", name: "iShares Core S&P 500", symbol: "IVV", type: "etf", finnhubSymbol: "IVV", logoUrl: "https://logo.clearbit.com/ishares.com", fallbackColor: "#000", displayDecimals: 2, description: "ETF S&P 500, iShares" },
    { slug: "vti", name: "Vanguard Total Stock", symbol: "VTI", type: "etf", finnhubSymbol: "VTI", logoUrl: "https://logo.clearbit.com/vanguard.com", fallbackColor: "#00A4EF", displayDecimals: 2, description: "ETF marché total US" },
    { slug: "iwm", name: "iShares Russell 2000", symbol: "IWM", type: "etf", finnhubSymbol: "IWM", logoUrl: "https://logo.clearbit.com/ishares.com", fallbackColor: "#003B71", displayDecimals: 2, description: "ETF Russell 2000, small caps US" },
    { slug: "vea", name: "Vanguard FTSE Developed", symbol: "VEA", type: "etf", finnhubSymbol: "VEA", logoUrl: "https://logo.clearbit.com/vanguard.com", fallbackColor: "#00A4EF", displayDecimals: 2, description: "ETF marchés développés hors US" },
    { slug: "vwo", name: "Vanguard FT Emerging", symbol: "VWO", type: "etf", finnhubSymbol: "VWO", logoUrl: "https://logo.clearbit.com/vanguard.com", fallbackColor: "#00A4EF", displayDecimals: 2, description: "ETF marchés émergents" },
    { slug: "bnd", name: "Vanguard Total Bond", symbol: "BND", type: "etf", finnhubSymbol: "BND", logoUrl: "https://logo.clearbit.com/vanguard.com", fallbackColor: "#00A4EF", displayDecimals: 2, description: "ETF obligations total market" },
    { slug: "vnq", name: "Vanguard Real Estate", symbol: "VNQ", type: "etf", finnhubSymbol: "VNQ", logoUrl: "https://logo.clearbit.com/vanguard.com", fallbackColor: "#00A4EF", displayDecimals: 2, description: "ETF immobilier/REITs US" },
];

export const ASSET_REGISTRY: Record<string, AssetMeta> = Object.fromEntries(
    [...crypto, ...forex, ...commodities, ...indices, ...stocks, ...etfs].map((a) => [a.slug, a])
);

export function getAsset(slug: string): AssetMeta | undefined {
    return ASSET_REGISTRY[slug.toLowerCase()];
}

export function getAssetBySymbol(symbol: string): AssetMeta | undefined {
    const s = symbol.toUpperCase();
    return Object.values(ASSET_REGISTRY).find((a) => a.symbol === s);
}

export function resolveAsset(input: string): { asset: AssetMeta; redirectSlug?: string } | undefined {
    const lowered = input.toLowerCase();
    const bySlug = ASSET_REGISTRY[lowered];
    if (bySlug) return { asset: bySlug };
    const bySymbol = Object.values(ASSET_REGISTRY).find((a) => a.symbol.toLowerCase() === lowered);
    if (bySymbol) return { asset: bySymbol, redirectSlug: bySymbol.slug };
    return undefined;
}

export function getAllSlugs(): string[] {
    return Object.keys(ASSET_REGISTRY);
}

export function getAssetsByType(type: AssetType): AssetMeta[] {
    return Object.values(ASSET_REGISTRY).filter((a) => a.type === type);
}
